# Generated by Django 2.2.3 on 2019-07-17 20:33

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20190717_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='access_key',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(max_length=63, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
