# Generated by Django 2.2.3 on 2019-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20190730_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='content_type',
            field=models.CharField(default='', max_length=128),
        ),
    ]
